name: php-demo
services:
  app:
    container_name: php
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ../:/app
      - /app/vendor
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: always
    volumes:
      - ../src:/app/src
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 8000:80
    
    
    